// this works from LINKEDIN ONLY

// cover letter examples
// https://docs.google.com/document/d/197PHCUCWxRQMTdfzMkC21h0ux6shWjjOATf7QzsgRb4/edit

let jobTitle = document.getElementsByClassName("jobs-details-top-card__job-title t-20 t-black t-normal")[0].innerText.toLowerCase();
let companyName = document.getElementsByClassName("jobs-details-top-card__company-url t-black--light t-normal ember-view")[0].innerText.trim();
let companyDetails = document.getElementsByClassName("jobs-box__html-content jobs-description-content__text t-14 t-normal")["job-details"].getElementsByTagName("span")[document.getElementsByClassName("jobs-box__html-content jobs-description-content__text t-14 t-normal")["job-details"].getElementsByTagName("span").length - 1 ].innerText;
let regexEmployees = / employees/gi;
let regexComma = /,/gi;
let regexAfterComma = /\W[^,]*$/gi;
let regexMetroArea = /Metropolitan Area/gi;
let companyType = document.getElementsByClassName("jobs-details-job-summary__text--ellipsis")[3].innerText.toLowerCase();
let companyEmployeeCount = document.getElementsByClassName("jobs-details-job-summary__text--ellipsis")[2].innerText;
let mySkillsCore = ["javascript", "react", "ruby", "redux"];
let mySkillsDatabase = ["sql", "mysql", "postgresql", "postgresql", "sqlite",];
let mySkillsUI = ["bootstrap", "material", "semantic", "css", "bootstrap"];
let mySkillsVersionControl = ["git", "github", "api"];
let companyCount = parseInt(companyEmployeeCount.replace(regexEmployees, "").replace(regexComma, ""));
let companyDetailsCleanedArray = companyDetails.toLowerCase().replace(regexComma, "").replace(/\//, " ").split(" ");

companySize = (companyCount) => {
	if (companyCount < 501) {
	return "small and intimate";
    } else if (companyCount < 1000) {
        return "medium and dynamic";
    } else 
        return "large and diverse";
    
}
// console.log(companySize(companyCount))
companyLocation = () => {
	if (document.getElementsByClassName("jobs-details-top-card__exact-location t-black--light link-without-visited-state")[0] != undefined) {
		return document.getElementsByClassName("jobs-details-top-card__exact-location t-black--light link-without-visited-state")[0].innerText.trim().replace(regexAfterComma, "").replace(regexMetroArea, "")
	} else if (document.getElementsByClassName("jobs-details-top-card__bullet")[0] != undefined) {
		return document.getElementsByClassName("jobs-details-top-card__bullet")[0].innerText.trim().replace(regexAfterComma, "").replace(regexMetroArea, "")
	} 
}
// console.log(companyLocation())
companyContact = () => {
	if (document.getElementsByClassName("jobs-poster__name t-14 t-black t-bold mb0")[0] != undefined) {
		return document.getElementsByClassName("jobs-poster__name t-14 t-black t-bold mb0")[0].innerText.split(" ")[0]
	} else
		return "hiring manager"
}
// console.log(companyContact())
teamFiller = (companySize) => {
	if (companySize.includes("small")) {
		return "and be able to have a postive impact with my colleagues in a tight-knit team"
	} else if (companySize.includes("medium")) {
		return "and be able to have a postive impact with my colleagues in an organized team"
	} else if (companySize.includes("large")) {
		return "and be able to have a postive impact with my colleagues in a scaled team"
	}
}
// console.log(teamFiller(companySize))
skillMatching = (companySkills, mySkills) => {
	let matchingSkills = mySkills.filter(skill => companySkills.includes(skill));
	// console.log(matchingSkills);
	return matchingSkills;
}
// console.log(skillMatching(companyDetails))

let coreSkill1 = skillMatching(companyDetailsCleanedArray, mySkillsCore)[0] ? `${skillMatching(companyDetailsCleanedArray, mySkillsCore)[0].toString()}` : "";
let coreSkill2 = skillMatching(companyDetailsCleanedArray, mySkillsCore)[1] ? ` and ${skillMatching(companyDetailsCleanedArray, mySkillsCore)[1].toString()}` : "";


console.log(`Hello ${companyContact()},
I saw the ${jobTitle} position at ${companyName} in ${companyLocation()}, and am extremely interested. I've included my resume, and when comparing my skills to the qualifications, feel that I would be a great fit for this position. I've always had a strong desire and passion for the ${companyType} industry. I would love to be part of a team in a ${companySize(companyCount)} company, ${teamFiller(companySize(companyCount))}.
\n
I noticed the request for ${coreSkill1}${coreSkill2}. Those are some of my favorite tools and think you'll find some of my recent projects relevant (www.elijahsamuels.com). My most recent project is actually what you're reading right now: an autogenerated cover letter.
\n
Having organized hundreds of musicians throughout the midwestern US, I know firsthand how imperative clear communication is, and to have a positive attitude through all situations. I love debugging problems to come up a working solution, and then refactoring them into something elegant. I'm genuinely fascinated by the seemingly infinite number of technologies, and strive to learn as much as I can.
\n
I'd love to talk with you more about ${coreSkill1}${coreSkill2}.

Thank you for your time and consideration,
Elijah
`.replace("  ", " "))
